command_timeout = 5000
add_newline = true
# A continuation prompt that displays two filled-in arrows
continuation_prompt = '[‚ñ∂‚ñ∂](bold grey)'

format = """
[ÓÇ∂](bg:wa_clear fg:wa_grey)\
$os\
$username\
[ÓÇ∞](fg:wa_grey bg:wa_blue)\
$directory\
[ÓÇ∞](fg:wa_blue bg:wa_gold)\
$time\
[ÓÇ∞](fg:wa_gold bg:wa_clear)\
$fill\
[‚óÄ](fg:wa_grey bg:wa_grey)\
$git_branch\
$git_status\
$lua\
$python\
$nodejs\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
[‚ï∞‚îÄ‚ùØ$character](fg:wa_green)
"""

palette = 'watzen'

[palettes.watzen]
wa_green = '#009b00'
wa_orange = '#E95420'
wa_black = '#000000'
wa_grey = '#363638'
wa_clear = '#030B16'
wa_blue = '#0c5deb'
wa_white = '#fbf1c7'
wa_gold = '#ccb233'
wa_purple = '#5306bf'
wa_red = '#d93030'


[os]
disabled = false
style = 'bg:wa_grey fg:wa_green'

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "Û∞£á"
Artix = "Û∞£á"
EndeavourOS = "ÔÜó"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"
Pop = "Ôå™"

[username]
show_always = true
style_user = 'bg:wa_grey fg:wa_green'
style_root = 'bg:wa_grey fg:wa_white'
format = '[ $user ]($style)'

[directory]
format = "[ üìÅ $path ]($style)"
style = "fg:wa_white bg:wa_blue"
truncation_length = 3
truncation_symbol = '.../'
truncate_to_repo = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:wa_gold"
format = '[[ Û±ëç $time ](bg:wa_gold fg:wa_black)]($style)'

# Replace the '‚ï¨√¥‚î¨√ë‚î¨‚ïó' symbol in the prompt with '‚ï¨√¥Œì√©¬∫‚î¨√∫'
[character] # The name of the module we are configuring is 'character'
# A continuation prompt that displays two filled-in arrows
success_symbol = '[‚ñ∂](bold green)'

[fill]
symbol = ' '

[cmd_duration]
format = '\[[‚è± $duration]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[git_branch]
style = 'fg:wa_gold bg:wa_grey'
symbol = 'Ôêò '
format = '[on ](fg:white bg:wa_grey)[$symbol$branch ]($style)'

[git_status]
style = 'bg:wa_grey fg:wa_gold'
format = '([\[$all_status$ahead_behind\]]($style))'

[python]
style = 'yellow'
symbol = "Óàµ "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = '${raw}'
pyenv_version_name = false
pyenv_prefix = ''
